<?php
/**
 * PURE FRONTEND FILE - plain description, not a function skeleton.
 *
 * WordPress automatically uses this template whenever someone views ONE
 * "Manual Document" post - i.e. one digitized PDF, now rendered as a
 * full webpage.
 *
 * What it will show:
 * - The document's title, document number, and revision/effective date
 *   at the top of the page.
 * - A row of tab buttons across the top, one per Section, generated by
 *   looping over that document's "sections" repeater field (via Pods'
 *   field-access functions) - nothing hardcoded, so any number of
 *   sections in any order renders correctly.
 * - Below the tabs, one content panel per section (only the active
 *   section is visible at a time; assets/tabs.js controls the
 *   show/hide behavior in the browser).
 * - A signature block near the bottom, looping over the "signatories"
 *   repeater field, showing each person's name, title, and signature
 *   image (if one was attached).
 * - The site's shared header/navigation/footer via get_header() and
 *   get_footer(), so it matches every other page on the site.
 *
 * This file only displays already-structured data pulled from Pods
 * fields - it holds no original business logic, which is why it is
 * described here rather than broken into functions.
 */
