<?php
/**
 * PURE FRONTEND FILE - plain description, not a function skeleton.
 *
 * WordPress automatically uses this template whenever someone views ONE
 * "Manual Document" post - i.e. one digitized PDF, now rendered as a
 * full webpage.
 *
 * What it will show:
 * - The document's title, document number, and revision/effective date
 *   at the top of the page.
 * - A row of tab buttons across the top, one per Section, generated by
 *   looping over the related "section" posts. NOTE: as of the
 *   "no true repeater field group in core Pods" fix (see
 *   pods-repeater-issue-and-fix.md), "sections" is a Pods Relationship
 *   field on manual_document rather than a repeater field, so this loop
 *   iterates over related post objects (e.g. via Pods'
 *   `pods_field('sections')` / `$pod->field('sections')`, which for a
 *   Relationship field returns the related "section" posts, each with
 *   its own `section_title`/`section_body`/`section_order` fields) -
 *   still nothing hardcoded, so any number of sections in any order
 *   renders correctly. The list should be sorted by each related post's
 *   `section_order` field before rendering, since a Relationship field
 *   does not guarantee that order on its own.
 * - Below the tabs, one content panel per section (only the active
 *   section is visible at a time; assets/tabs.js controls the
 *   show/hide behavior in the browser).
 * - A signature block near the bottom, looping over the related
 *   "signatory" posts (same Relationship-field pattern as "sections"
 *   above, sorted by `signatory_order`), showing each person's name,
 *   title, and signature image (if one was attached).
 * - The site's shared header/navigation/footer via get_header() and
 *   get_footer(), so it matches every other page on the site.
 *
 * This file only displays already-structured data pulled from Pods
 * fields (now via related "section"/"signatory" posts rather than
 * repeater rows) - it holds no original business logic, which is why it
 * is described here rather than broken into functions.
 */
